accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('',views.index,name='index'),
    path('home/',views.home,name='home'),
    path('signup/',views.signup,name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/login/',include('django.contrib.auth.urls')),
    path('accounts/logout/',include('django.contrib.auth.urls')),
]

accounts/models.py
from django.db import models

accounts/forms.py
from django.contrib.auth import forms as auth_forms

class LoginForm(auth_forms.AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['placeholder'] = field.label

accounts/views.py
from django.shortcuts import render,HttpResponseRedirect,redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login
from django.contrib.auth.forms import UserCreationForm

def index(request):
    return render(request,'accounts/index.html')

@login_required
def home(request):
    return render(request,'accounts/home.html')

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST) # 入力された値からUserインスタンスを作成
        if form.is_valid():
            new_user = form.save()
            input_username = form.cleaned_data['username']
            input_password = form.cleaned_data['password1']
            # フォームの入力値が認証できればユーザーオブジェクト、できなければNoneを返す
            new_user = authenticate(username = input_username, password = input_password)
            # 認証成功時のみ、ユーザーをログインさせる
            if new_user is not None:
                login(request, new_user)
                return redirect('accounts:index')
            return render(request,'registration/signup.html',{'form':form})
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form':form})

accounts/templates/accounts/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ホーム画面</title>
</head>
<body>
    <h1>ホーム画面</h1>

    <p>こんにちは{{ user.username }}さん</p>

    <p><a href="{% url 'logout' %}">ログアウト</a></p>
</body>
</html>

accounts/templates/accounts/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>トップ画面</title>
</head>
<body>
    <h1>トップ画面</h1>
    {% if user.is_authenticated %}
    <p><a href="{% url 'logout' %}">ログアウト</a></p>
    {% else %}
    <p><a href="{% url 'login' %}">ログイン</a></p>
    <p><a href="{% url 'accounts:signup' %}">登録</a></p>
    {% endif %}
</body>
</html>